In [20]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [21]:
import numpy as np
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/inventory_management_dirty.csv')

In [22]:
df.head()

,Product_ID,Product_Name,Category,Supplier,Warehouse,Quantity_Stock,Unit_Price,Purchase_Date,Expiry_Date,Reorder_Level,Sales_Last_Month,Damaged_Items,Status
0,P1179,Offise Chair,clothing,XYZ Supplies,Bangalore,309,not available,6/13/2023,32-13-2023,40.0,227.0,14.0,Available
1,P1171,Jeans,Groccery,Prime Distributors,delhi,NaN,363.59,10/19/2023,11/11/2026,20.0,112.0,15.0,In Stock
2,P1072,Dinig Table,furniture,Quick Supply Co,New Delhi,316,4005.06,11/5/2022,2/6/2021,13.0,249.0,5.0,In Stock
3,P1090,Mixer Grinder,Furnture,Prime Distributors,MUMBAI,unknown,-1600.4,6/6/2022,9/3/2024,6.0,222.0,3.0,available
4,P1055,Mobile Phone,sports,abc traders,KOLKATA,68,972.13,12/15/2022,1/24/2024,16.0,207.0,2.0,Available

In [23]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_ID        200 non-null    object
 1   Product_Name      200 non-null    object
 2   Category          193 non-null    object
 3   Supplier          193 non-null    object
 4   Warehouse         193 non-null    object
 5   Quantity_Stock    184 non-null    object
 6   Unit_Price        197 non-null    object
 7   Purchase_Date     192 non-null    object
 8   Expiry_Date       192 non-null    object
 9   Reorder_Level     178 non-null    float64
 10  Sales_Last_Month  185 non-null    float64
 11  Damaged_Items     183 non-null    float64
 12  Status            193 non-null    object
dtypes: float64(3), object(10)
memory usage: 20.4+ KB
None

In [24]:
print(df.describe())

       Reorder_Level  Sales_Last_Month  Damaged_Items
count     178.000000        185.000000     183.000000
mean       25.185393        834.362162      27.967213
std        13.877365       5018.899288      82.461373
min        -5.000000          3.000000       0.000000
25%        14.250000         67.000000       4.000000
50%        24.000000        147.000000       8.000000
75%        36.000000        226.000000      13.000000
max        50.000000      46675.000000     497.000000

In [25]:
print("Missing items check:\n", df.isnull().sum())

Missing items check:
 Product_ID           0
Product_Name         0
Category             7
Supplier             7
Warehouse            7
Quantity_Stock      16
Unit_Price           3
Purchase_Date        8
Expiry_Date          8
Reorder_Level       22
Sales_Last_Month    15
Damaged_Items       17
Status               7
dtype: int64

In [26]:
df['Category'] = df['Category'].fillna(df['Category'].mode()[0])

In [27]:
df['Supplier'] = df['Supplier'].fillna('Unknown')

In [28]:
df['Warehouse'] = df['Warehouse'].fillna('Unknown')

In [30]:
print(df.dtypes)

Product_ID           object
Product_Name         object
Category             object
Supplier             object
Warehouse            object
Quantity_Stock       object
Unit_Price           object
Purchase_Date        object
Expiry_Date          object
Reorder_Level       float64
Sales_Last_Month    float64
Damaged_Items       float64
Status               object
dtype: object

In [33]:
df['Quantity_Stock'].unique()

array(['309', nan, '316', 'unknown', '68', '184', '277', '128', '408',
       '200', '27', '71', '0', '118', 'error', '313', '130', '485', '49',
       '169', '360', '302', '367', '369', '259', '91', '230', '117',
       '234', '436', '238', '372', '493', '137', '220', '413', '252',
       '218600', '158', '407', '432', '133', '337', '445', '195', '171',
       '435', '97', '134', '191', '454', '405', '355', '402', '58', '317',
       '397', '93', '214', '162', '232', '-1', '424', '61', '474', '421',
       '495', '396', '113', '150', '425', '254', '5', '225', '101', '153',
       '411', '413546', '351', '122', '143', '181', '28', '-47', '442',
       '25', '456', '14', '343', '268', '132', '266', '218', '393', '387',
       '312', '164', '265', '64', '335', '350', '995404', '428', '15',
       '374', '494', '244', '458', '142', '476', '187', '348', '378',
       '21', '849484', '207', '229', '92', '194', '399'], dtype=object)

In [34]:
df['Quantity_Stock'] = pd.to_numeric(df['Quantity_Stock'], errors='coerce')

In [35]:
df['Quantity_Stock'].dtypes

dtype('float64')

In [74]:
df.loc[df['Quantity_Stock'] < 0, 'Quantity_Stock'] = np.nan

In [75]:
df['Quantity_Stock'] = df['Quantity_Stock'].fillna(df['Quantity_Stock'].mean())

In [79]:
df['Quantity_Stock'] = df['Quantity_Stock'].astype(int)

In [37]:
df['Unit_Price'].dtypes

dtype('O')

In [38]:
df['Unit_Price'].unique()

array(['not available', '363.59', '4005.06', '-1600.4', '972.13',
       '$3,233.47 ', '₹4,987.31', '2624.48', '4012.82', '4700.16',
       '$3,753.42 ', '$3,670.39 ', '2106.45', '2383.74', nan, '####',
       '3915.09', '-2639.99', '₹4,615.70', '3146.57', '4433.32',
       '3695.32', '4999.54', '1949.34', '2946.04', '3133.71', '2709.67',
       '₹3,386.35', '1499.24', '$2,432.00 ', '94.29', '3078.47', '521.11',
       '4167.81', '₹486.93', '312.46', '-2088.67', '₹3,433.41', '-564.44',
       '1298.61', '712.98', '746.97', '3455.48', '3252.83', '$1,720.97 ',
       '386.83', '3938.76', '853.23', '1992.8', '3664.99', '-4866.3',
       '3489.07', '3999.83', '2888.09', '3112.4', '320', '₹3,662.70',
       '$125.27 ', '-2229.78', '4355.54', '-3790.17', '3983.17',
       '2921.83', '2439.16', '218.71', '4496.13', '538.58', '1180.32',
       '2423.31', '1166.96', '3488.32', '1343.95', '4112.36', '1768.08',
       '-633.95', '2057.78', '3401', '-588.45', '$4,023.39 ',
       '$1,518.57 ', '3716.98', '4891.38', '689.26', '₹218.45', '1743.65',
       '1830.8', '₹2,485.96', '810.11', '1655.16', '$1,322.34 ',
       '$1,596.84 ', '₹4,245.74', '-1915.54', '2610.48', '173.24',
       '1618.38', '3156.78', '1910.61', '-3530', '3606.62', '4533.57',
       '$3,879.97 ', '174.18', '2037.82', '2588.04', '973.67', '2361.39',
       '1569.28', '2267.49', '-2504.6', '₹2,078.21', '3922.11', '3761.37',
       '4855.49', '1479.8', '-3313.07', '2526.04', '2768.8', '3078.89',
       '3740.1', '₹3,576.37', '4519.34', '2592.7', '$46.02 ', '3501.08',
       '4706.3', '2085.5', '1653.13', '4357.81', '4205.58', '2476.59',
       '-3404.33', '1112.95', '$4,150.79 ', '₹3,231.05', '4200.26',
       '1823.08', '1920.44', '2224.82', '2612.04', '4837.05', '₹4,289.68',
       '3626.97', '$4,999.88 ', '$3,014.07 ', '3594.86', '117.23',
       '4903.64', '1046.11', '3400.8', '1006.34', '$3,690.69 ', '4198.5',
       '₹4,146.98', '2541.5', '398.53', '3031.97', '2439.44', '4961.59',
       '4975.54', '-779.17', '2655.96', '3060.68', '1830.51', '3240.43'],
      dtype=object)

In [42]:
df['Unit_Price'] = df['Unit_Price'].astype(str)

df['Unit_Price'] = df['Unit_Price'].str.replace('â‚¹', '', regex=False)
df['Unit_Price'] = df['Unit_Price'].str.replace('$', '', regex=False)
df['Unit_Price'] = df['Unit_Price'].str.replace('₹', '', regex=False)
df['Unit_Price'] = df['Unit_Price'].str.replace(',', '', regex=False)

df['Unit_Price'] = pd.to_numeric(df['Unit_Price'], errors='coerce')

In [43]:
# Negative prices treated as invalid values
df.loc[df['Unit_Price'] < 0, 'Unit_Price'] = np.nan
df['Unit_Price'] = df['Unit_Price'].fillna(df['Unit_Price'].mean())

In [44]:
df['Purchase_Date'].unique()

array(['6/13/2023', '10/19/2023', '11/5/2022', '6/6/2022', '12/15/2022',
       '4/6/2022', '1/3/2022', '2/11/2022', '21-10-2022', '12/12/2023',
       '7/28/2023', '9/11/2023', nan, '7/5/2022', '6/10/2023',
       '5/22/2023', 'not a date', '8/9/2022', '2/10/2022', '14-02-2022',
       '7/23/2023', '12/24/2023', '28-01-2022', '10/24/2023', '1/11/2023',
       '12/7/2022', '1/12/2023', '11/22/2022', '25-06-2023', '12/3/2022',
       '11/16/2023', '13-03-2023', '24-11-2022', '2/13/2023', '2/19/2023',
       '7/4/2022', '12/9/2022', '4/27/2022', '3/25/2023', '8/3/2022',
       '14-10-2023', '4/6/2023', '4/17/2023', '6/11/2023', '7/17/2022',
       '3/22/2022', '7/21/2022', '15-09-2023', '3/1/2022', '7/22/2022',
       '21-10-2023', '10/22/2022', '3/13/2023', '4/25/2022', '12/23/2023',
       '10/20/2022', '6/14/2022', '9/6/2023', '6/18/2022', '4/26/2022',
       '16-09-2022', '17-06-2022', '12/11/2023', '10/21/2022', '7/6/2023',
       '4/11/2022', '8/22/2023', '3/21/2022', '21-07-2022', '12/9/2023',
       '7/15/2023', '11/25/2023', '3/4/2022', '2/5/2023', '2/4/2023',
       '24-12-2023', '11/28/2022', '3/14/2022', '4/3/2022', '4/7/2022',
       '11/8/2022', '18-09-2023', '28-05-2023', '10/4/2023', '4/12/2022',
       '1/21/2023', '5/27/2023', '5/9/2023', '6/23/2022', '10/1/2023',
       '2/25/2022', '7/22/2023', '12/20/2023', '4/22/2022', '11/15/2022',
       '26-08-2022', '8/8/2023', '12/25/2022', '3/27/2023', '12/26/2023',
       '1/7/2023', '28-04-2022', '12/24/2022', '9/24/2022', '4/23/2022',
       '11/7/2023', '12/2/2022', '8/14/2022', '2/11/2023', '9/10/2022',
       '9/16/2023', '4/14/2022', '4/4/2023', '9/7/2023', '11/4/2023',
       '10/18/2023', '8/8/2022', '3/2/2022', '2/24/2023', '11/2/2022',
       '9/14/2023', '4/2/2022', '16-08-2023', '2/25/2023', '8/6/2022',
       '6/22/2023', '3/6/2022', '9/22/2023', '4/12/2023', '6/12/2022',
       '11/19/2023', '11/4/2022', '1/15/2022', '14-06-2023', '8/11/2022',
       '10/4/2022', '1/16/2022', '2/16/2022', '8/25/2022', '7/7/2022',
       '17-10-2022', '2/17/2023', '4/15/2023', '4/2/2023', '3/11/2022',
       '6/16/2023', '8/4/2022', '10/24/2022', '12/11/2022', '1/4/2023',
       '8/4/2023', '3/12/2023', '20-03-2023', '22-05-2023', '12/19/2023',
       '10/13/2023', '22-04-2022', '9/5/2022', '7/19/2022', '9/21/2022',
       '11/9/2022', '11/14/2023'], dtype=object)

In [45]:
df['Purchase_Date'] = pd.to_datetime(df['Purchase_Date'], errors='coerce')

In [46]:
df['Purchase_Date'] = df['Purchase_Date'].fillna(df['Purchase_Date'].mode()[0])

In [47]:
df['Expiry_Date'].unique()

array(['32-13-2023', '11/11/2026', '2/6/2021', '9/3/2024', '1/24/2024',
       '3/19/2024', '4/3/2026', '2/28/2024', '6/19/2025', '8/9/2024', nan,
       '10/13/2026', 'not a date', '10/12/2020', '9/3/2026', '18-03-2025',
       '5/3/2020', '4/20/2024', '6/12/2024', '20-01-2024', '11/4/2025',
       '22-12-2025', '6/2/2026', '6/23/2026', '14-02-2026', '12/3/2025',
       '1/20/2026', '5/2/2026', '8/20/2020', '3/3/2026', '5/5/2025',
       '5/27/2026', '7/6/2024', '9/26/2026', '10/6/2025', '13-10-2024',
       '6/19/2024', '2/6/2026', '8/3/2026', '2/21/2024', '8/16/2025',
       '2/19/2021', '20-01-2026', '10/17/2026', '10/19/2024', '4/1/2026',
       '9/10/2026', '5/23/2024', '23-05-2026', '8/6/2025', '4/7/2020',
       '10/14/2026', '3/11/2025', '5/1/2026', '16-04-2026', '21-03-2024',
       '18-09-2024', '10/20/2026', '7/3/2025', '11/27/2026', '11/10/2026',
       '8/4/2024', '20-12-2024', '8/20/2024', '18-05-2024', '4/10/2026',
       '21-03-2026', '12/28/2025', '5/17/2025', '4/18/2026', '13-09-2026',
       '4/17/2024', '9/14/2025', '5/9/2025', '10/25/2026', '3/24/2024',
       '5/24/2025', '12/24/2026', '11/6/2026', '12/22/2024', '1/22/2026',
       '1/25/2025', '11/3/2026', '16-09-2024', '10/5/2026', '5/2/2025',
       '1/21/2021', '24-11-2024', '11/3/2024', '11/27/2024', '4/1/2024',
       '3/28/2025', '4/20/2025', '1/11/2024', '5/4/2024', '11/5/2026',
       '10/2/2021', '1/7/2024', '4/15/2024', '11/19/2024', '11/2/2020',
       '5/18/2025', '10/3/2026', '12/13/2026', '18-12-2024', '16-03-2026',
       '18-09-2025', '2/23/2025', '5/3/2026', '14-06-2024', '8/8/2025',
       '9/6/2026', '21-10-2025', '7/11/2024', '27-12-2025', '7/14/2020',
       '8/10/2024', '12/21/2026', '3/12/2024', '3/10/2024', '9/1/2024',
       '10/8/2024', '2/16/2026', '16-01-2025', '9/1/2026', '18-02-2024',
       '5/12/2024', '8/23/2026', '10/5/2024', '5/6/2026', '8/23/2024',
       '11/21/2020', '11/15/2024', '3/9/2024', '3/23/2024', '4/23/2026',
       '6/22/2024', '1/12/2025', '16-12-2024', '11/19/2020', '1/4/2025',
       '1/19/2024', '5/21/2025', '17-02-2024', '6/11/2024', '13-02-2025',
       '8/5/2026', '9/21/2024', '3/2/2025', '5/15/2025', '9/17/2025',
       '10/21/2025', '1/3/2025', '2/20/2026'], dtype=object)

In [48]:
df['Expiry_Date'] = pd.to_datetime(df['Expiry_Date'], errors='coerce')

/tmp/ipykernel_1934/811135647.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Expiry_Date'] = pd.to_datetime(df['Expiry_Date'], errors='coerce')

In [49]:
df['Expiry_Date'].isna().sum()

np.int64(30)

In [52]:
df['Expiry_Date'].dtypes

dtype('<M8[ns]')

In [53]:
df['Expiry_Date'] = df['Expiry_Date'].fillna(df['Expiry_Date'].mode()[0])

In [54]:
print("Missing items check:\n", df.isnull().sum())

Missing items check:
 Product_ID           0
Product_Name         0
Category             0
Supplier             0
Warehouse            0
Quantity_Stock       0
Unit_Price           0
Purchase_Date        0
Expiry_Date          0
Reorder_Level       22
Sales_Last_Month    15
Damaged_Items       17
Status               7
dtype: int64

In [56]:
df['Reorder_Level'].unique()

array([40., 20., 13.,  6., 16.,  8., 41., nan, 12., 30., 39., 26.,  7.,
       24., 18., 50., 14., 28.,  5., 49., 33., 10.,  0., 27., 25., 45.,
       32., 37., 36., 15., -5., 42., 48., 19., 29., 35., 38., 17., 46.,
       23., 22., 44., 47., 31., 11., 21., 34.,  9., 43.])

In [57]:
df.loc[df['Reorder_Level'] < 0, 'Reorder_Level'] = np.nan

In [58]:
df['Reorder_Level'].isna().sum()

np.int64(23)

In [59]:
df['Reorder_Level'] = df['Reorder_Level'].fillna(df['Reorder_Level'].median()).astype(int)

In [61]:
df['Reorder_Level'].min()

0

In [62]:
df['Damaged_Items'].unique()

array([ 14.,  15.,   5.,   3.,   2.,  13., 295.,  11.,   1.,   9.,  nan,
         7.,  12.,  61., 184., 375., 379., 275.,  10.,   4.,   8.,   6.,
         0., 443., 164., 106., 497., 377., 465., 207.])

In [63]:
df['Damaged_Items'] = df['Damaged_Items'].fillna(df['Damaged_Items'].median())

In [65]:
df['Sales_Last_Month'].unique()

array([2.2700e+02, 1.1200e+02, 2.4900e+02, 2.2200e+02, 2.0700e+02,
       9.5000e+01, 2.1200e+02, 2.4700e+02, 5.6000e+01,        nan,
       1.8300e+02, 2.8700e+02, 1.8700e+02, 1.6700e+02, 9.0000e+01,
       7.6000e+01, 1.6200e+02, 2.1600e+02, 3.3000e+01, 2.5700e+02,
       2.0500e+02, 1.8800e+02, 1.2000e+02, 2.1300e+02, 2.9900e+02,
       1.5300e+02, 2.3000e+01, 2.9000e+02, 4.0000e+01, 1.5400e+02,
       2.8000e+01, 7.7000e+01, 2.6600e+02, 2.8500e+02, 2.7600e+02,
       8.0000e+00, 2.3100e+02, 2.6700e+02, 2.2600e+02, 1.6500e+02,
       3.6000e+01, 2.1500e+02, 5.5000e+01, 2.8000e+02, 5.4000e+01,
       3.4659e+04, 1.6400e+02, 3.0000e+00, 3.0000e+01, 7.2000e+01,
       7.8000e+01, 4.2000e+01, 2.3500e+02, 6.0000e+01, 1.2800e+02,
       5.3000e+01, 2.1000e+01, 2.0100e+02, 2.7300e+02, 1.6000e+02,
       2.1100e+02, 3.2000e+01, 1.9000e+02, 1.9400e+02, 1.1500e+02,
       6.7000e+01, 1.6000e+01, 1.0100e+02, 2.4000e+01, 2.7900e+02,
       1.4700e+02, 5.0000e+01, 7.0000e+00, 4.5000e+01, 1.2900e+02,
       1.8400e+02, 1.8200e+02, 1.3100e+02, 1.4200e+02, 1.2200e+02,
       4.3000e+01, 2.9300e+02, 1.9000e+01, 8.2000e+01, 2.6000e+01,
       9.2000e+01, 2.3000e+02, 1.3600e+02, 2.6100e+02, 2.2500e+02,
       7.1000e+01, 9.3000e+01, 5.8000e+01, 4.6675e+04, 1.4100e+02,
       2.6500e+02, 2.2400e+02, 1.5000e+01, 6.6000e+01, 2.7800e+02,
       1.7500e+02, 4.6000e+01, 1.2100e+02, 1.3900e+02, 6.3000e+01,
       6.5000e+01, 4.0000e+00, 8.0000e+01, 7.5000e+01, 2.4300e+02,
       1.0500e+02, 1.0973e+04, 1.1700e+02, 1.4900e+02, 2.4600e+02,
       1.1900e+02, 3.9000e+01, 8.4000e+01, 4.1000e+01, 2.3300e+02,
       1.4500e+02, 2.9500e+02, 2.7700e+02, 2.6300e+02, 1.2300e+02,
       1.3500e+02, 7.0000e+01, 3.5470e+04, 1.8000e+02, 2.8900e+02])

In [66]:
df['Sales_Last_Month'] = df['Sales_Last_Month'].fillna(df['Sales_Last_Month'].median())

In [68]:
df['Status'].unique()

array([' Available ', '  In Stock  ', 'In Stock', 'available',
       '  Available  ', 'Available', '  out stock  ', 'Out of Stock',
       '  Out of Stock  ', 'out stock', '???', '  AVAILABLE  ',
       '  available  ', '   Available   ', nan, 'AVAILABLE'], dtype=object)

In [69]:
df['Status'] = df['Status'].astype(str)
df['Status'] = df['Status'].str.strip().str.lower()

In [70]:
df['Status'] = df['Status'].replace({
    'available': 'Available',
    'in stock': 'Available',
    'available ': 'Available',

    'out of stock': 'Out of Stock',
    'out stock': 'Out of Stock',
    'outstock': 'Out of Stock',

    '???': np.nan,
    'nan': np.nan
})

In [71]:
df['Status'] = df['Status'].fillna(df['Status'].mode()[0])

In [76]:
df.describe()

,Quantity_Stock,Unit_Price,Purchase_Date,Expiry_Date,Reorder_Level,Sales_Last_Month,Damaged_Items
count,200.000000,200.000000,200,200,200.000000,200.000000,200.000000
mean,15564.028600,2664.628217,2022-10-24 03:00:00,2025-04-28 21:00:00,25.200000,782.810000,26.270000
min,0.000000,46.020000,2022-01-03 00:00:00,2020-04-07 00:00:00,0.000000,3.000000,0.000000
25%,136.250000,1890.657500,2022-03-14 00:00:00,2024-08-22 06:00:00,16.000000,74.250000,4.000000
50%,317.000000,2664.628217,2022-09-22 12:00:00,2025-09-14 00:00:00,24.000000,147.000000,8.000000
75%,474.000000,3597.800000,2023-04-06 00:00:00,2026-05-06 00:00:00,34.250000,224.000000,13.000000
max,995404.000000,4999.880000,2023-12-26 00:00:00,2026-12-24 00:00:00,50.000000,46675.000000,497.000000
std,97506.874148,1245.107605,NaN,NaN,12.917986,4829.451048,79.057877

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Product_ID        200 non-null    object
 1   Product_Name      200 non-null    object
 2   Category          200 non-null    object
 3   Supplier          200 non-null    object
 4   Warehouse         200 non-null    object
 5   Quantity_Stock    200 non-null    float64
 6   Unit_Price        200 non-null    float64
 7   Purchase_Date     200 non-null    datetime64[ns]
 8   Expiry_Date       200 non-null    datetime64[ns]
 9   Reorder_Level     200 non-null    int64
 10  Sales_Last_Month  200 non-null    float64
 11  Damaged_Items     200 non-null    float64
 12  Status            200 non-null    object
dtypes: datetime64[ns](2), float64(4), int64(1), object(6)
memory usage: 20.4+ KB

In [80]:
df.to_csv('/content/drive/MyDrive/inventory_management_cleaned.csv', index=False)